/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 16 18:31:58 GMT 2025
 */

package maven;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import maven.Money;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Money_ESTest extends Money_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Money money0 = new Money(0, "Im)6m5pPdN'jtR!");
      money0.getCurrency();
      assertEquals(0, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Money money0 = new Money((-967), "");
      money0.getCurrency();
      assertEquals((-967), money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Money money0 = new Money(1049, "");
      int int0 = money0.getAmount();
      assertEquals(1049, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Money money0 = new Money((-967), "");
      int int0 = money0.getAmount();
      assertEquals((-967), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Money money0 = new Money((-2500), "");
      Money money1 = money0.add(money0);
      boolean boolean0 = money1.equals(money0);
      assertEquals((-2500), money0.getAmount());
      assertFalse(boolean0);
      assertFalse(money0.equals((Object)money1));
      assertEquals((-5000), money1.getAmount());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Money money0 = new Money((-716), (String) null);
      // Undeclared exception!
      try { 
        money0.add((Money) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("maven.Money", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Money money0 = new Money(0, (String) null);
      money0.getCurrency();
      assertEquals(0, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Money money0 = new Money(0, (String) null);
      int int0 = money0.getAmount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Money money0 = new Money(3792, ";V`N;Txb9%M5");
      boolean boolean0 = money0.equals(money0);
      assertTrue(boolean0);
      assertEquals(3792, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Money money0 = new Money(3792, ";V`N;Txb9%M5");
      Money money1 = new Money(3792, "JhgFN; -xa9YM5");
      boolean boolean0 = money1.equals(money0);
      assertEquals(3792, money1.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Money money0 = new Money(3792, ";V`N;Txb9%M5");
      Money money1 = money0.add(money0);
      boolean boolean0 = money1.equals(money0);
      assertEquals(3792, money0.getAmount());
      assertFalse(boolean0);
      assertFalse(money0.equals((Object)money1));
      assertEquals(7584, money1.getAmount());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Money money0 = new Money(0, (String) null);
      boolean boolean0 = money0.equals((Object) null);
      assertEquals(0, money0.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Money money0 = new Money(0, (String) null);
      // Undeclared exception!
      try { 
        money0.equals(money0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Money money0 = new Money(0, (String) null);
      Money money1 = money0.add(money0);
      assertEquals(0, money1.getAmount());
  }
}
